/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 11 21:42:52 GMT 2019
 */

package it.polimi.dagsymb.launchers;

import it.polimi.dagsymb.Louvain;
import it.polimi.dagsymb.LouvainConfig;
import org.junit.runner.RunWith;
import shaded.org.evosuite.runtime.EvoRunner;
import shaded.org.evosuite.runtime.EvoRunnerParameters;

import java.util.ArrayList;
import java.util.List;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LouvainLauncher/* extends Louvain_0_0_Test_scaffolding*/ {
 
  public static void main(String[] args) {
	  String IGuardEvalClassname = args[0]; // IGuardEvaluator implementation Class FQ Classname
	  String inputFile = args[1];
	  String outputFile = args[2];
      int parallelism = Integer.parseInt(args[3]);
      int minimumCompressionProgress = Integer.parseInt(args[4]);
	  int progressCounter = Integer.parseInt(args[5]);
	  String delimiter = args[6];

	  List<Long> sizes = new ArrayList<>();
	  for (int i = 7; i < args.length - 2; i++){
	      Long s = Long.parseLong(args[i]);
	      sizes.add(s);
      }

      String dataGen = args[args.length-2];
      String appName = args[args.length-1];

      boolean genData = false;
      String sparkAppName = "";
      if (dataGen != null && dataGen.startsWith("-g")) genData = true;
      if (appName != null && !appName.startsWith("-")) sparkAppName = appName;


      /*LouvainConfig louvainConfig0 = new LouvainConfig(
              "src/data/input/sample.txt",
              "src/data/output/",
              20,
              2000,
              1,
              ",");
              */
      LouvainConfig louvainConfig0 = new LouvainConfig(inputFile, outputFile, parallelism,
        	  minimumCompressionProgress, progressCounter, delimiter, genData, sparkAppName, sizes);

      Louvain louvain0 = new Louvain();

      louvain0.run0(louvainConfig0);
  }
  
}
