/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 11 15:23:25 GMT 2019
 */

package it.polimi.dagsymb;

import org.junit.Test;
import static org.junit.Assert.*;
import it.polimi.dagsymb.Louvain;
import it.polimi.dagsymb.LouvainConfig;
import org.junit.runner.RunWith;
import shaded.org.evosuite.runtime.EvoRunner;
import shaded.org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Louvain_0_12_Test extends Louvain_0_12_Test_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. it.polimi.dagsymb.Louvain.run(Lit/polimi/dagsymb/LouvainConfig;)V: path condition EvoSuiteWrapper_0_12 (id = 0)
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Louvain louvain0 = new Louvain();
      louvain0.addToFileLocal(1000000, (-318), 0);
      LouvainConfig louvainConfig0 = new LouvainConfig("|ByK|p4akgY.", "~XnD'7? wut=+q/`WN", (-1), (-1186), (-1), (String) null);
      louvain0.run0(louvainConfig0);
  }
}
